/** Client-safe BİST symbol lists (no yahoo-finance2 / Node deps). */

export const DEFAULT_BIST_SYMBOLS: string[] = [
  'XU100.IS',
  'THYAO.IS',
  'GARAN.IS',
  'ASELS.IS',
  'EREGL.IS',
];

export const BIST30_SYMBOLS: string[] = [
  'AKBNK.IS',
  'ALARK.IS',
  'ARCLK.IS',
  'ASELS.IS',
  'ASTOR.IS',
  'BIMAS.IS',
  'BRSAN.IS',
  'DOAS.IS',
  'EKGYO.IS',
  'ENKAI.IS',
  'EREGL.IS',
  'FROTO.IS',
  'GARAN.IS',
  'GUBRF.IS',
  'HEKTS.IS',
  'ISCTR.IS',
  'KCHOL.IS',
  'KONTR.IS',
  'KOZAL.IS',
  'KRDMD.IS',
  'ODAS.IS',
  'PETKM.IS',
  'PGSUS.IS',
  'SAHOL.IS',
  'SASA.IS',
  'SISE.IS',
  'TAVHL.IS',
  'TCELL.IS',
  'THYAO.IS',
  'TOASO.IS',
  'TUPRS.IS',
  'ULKER.IS',
  'VESTL.IS',
  'YKBNK.IS',
];
