import { BIST30_SYMBOLS } from '@/lib/bist-symbols';

/**
 * Max liquid BİST universe for Market Scanner (~BIST 100 + midcap liquidity).
 * Yahoo symbols end with .IS
 */
export const SCANNER_BIST_SYMBOLS = [
  'XU100.IS',
  'XU030.IS',
  ...BIST30_SYMBOLS,
  // Banks / holdings
  'HALKB.IS',
  'VAKBN.IS',
  'TSKB.IS',
  'SKBNK.IS',
  'ICBCT.IS',
  // Retail / consumer
  'AEFES.IS',
  'CCOLA.IS',
  'MGROS.IS',
  'SOKM.IS',
  'MAVI.IS',
  'BIZIM.IS',
  'INDES.IS',
  'TKNSA.IS',
  // Energy / industry
  'OTKAR.IS',
  'DOHOL.IS',
  'TKFEN.IS',
  'GESAN.IS',
  'EUREN.IS',
  'EUPWR.IS',
  'CWENE.IS',
  'ENJSA.IS',
  'AKSEN.IS',
  'AYDEM.IS',
  'ZOREN.IS',
  'CANTE.IS',
  'BIOEN.IS',
  'SMRTG.IS',
  // Mining / metals
  'KOZAA.IS',
  'IPEKE.IS',
  'PRKME.IS',
  'CEMTS.IS',
  'ISDMR.IS',
  'KCAER.IS',
  // Tech / defense / telecom
  'TTKOM.IS',
  'LOGO.IS',
  'NETAS.IS',
  'INDES.IS',
  'PAPIL.IS',
  'SDTTR.IS',
  'DESA.IS',
  // Auto / transport
  'ASUZU.IS',
  'TMSN.IS',
  'CLEBI.IS',
  'RYSAS.IS',
  'BEYAZ.IS',
  // RE / construction
  'ISGYO.IS',
  'ALGYO.IS',
  'PEKGY.IS',
  'VKGYO.IS',
  'YGGYO.IS',
  'NUGYO.IS',
  'SNGYO.IS',
  // Cement / materials
  'CIMSA.IS',
  'OYAKC.IS',
  'AKCNS.IS',
  'BUCIM.IS',
  'KONYA.IS',
  // Food / agri
  'TATGD.IS',
  'BANVT.IS',
  'KERVT.IS',
  'OYLUM.IS',
  'PNSUT.IS',
  // Misc liquid midcaps
  'EGEEN.IS',
  'TTRAK.IS',
  'VESBE.IS',
  'KARSN.IS',
  'BRISA.IS',
  'GOODY.IS',
  'AKSA.IS',
  'KORDS.IS',
  'PARSN.IS',
  'ALKIM.IS',
  'GSDHO.IS',
  'IHLAS.IS',
  'ANSGR.IS',
  'TURSG.IS',
  'ANHYT.IS',
  'AGHOL.IS',
  'GLYHO.IS',
  'NTHOL.IS',
  'BERA.IS',
  'KAREL.IS',
  'SELEC.IS',
  'QUAGR.IS',
  'MIATK.IS',
  'REEDR.IS',
  'BINHO.IS',
  'GRTHO.IS',
  'KLSER.IS',
  'YEOTK.IS',
  'GENIL.IS',
  'PASEU.IS',
  'OBAMS.IS',
  'KMPUR.IS',
] as const;

/** Unique BİST list (dedupe BIST30 overlaps) */
export const SCANNER_BIST_UNIQUE = [
  ...new Set(SCANNER_BIST_SYMBOLS.map((s) => s.toUpperCase())),
] as string[];

/** Curated fallback when full Binance book fails */
export const SCANNER_CRYPTO_SYMBOLS = [
  'BTCUSDT',
  'ETHUSDT',
  'BNBUSDT',
  'SOLUSDT',
  'XRPUSDT',
  'ADAUSDT',
  'DOGEUSDT',
  'AVAXUSDT',
  'DOTUSDT',
  'LINKUSDT',
  'MATICUSDT',
  'LTCUSDT',
  'UNIUSDT',
  'ATOMUSDT',
  'NEARUSDT',
  'APTUSDT',
  'ARBUSDT',
  'OPUSDT',
  'SUIUSDT',
  'PEPEUSDT',
  'SHIBUSDT',
  'TRXUSDT',
  'TONUSDT',
  'INJUSDT',
  'FETUSDT',
  'RENDERUSDT',
  'FILUSDT',
  'ICPUSDT',
  'IMXUSDT',
  'AAVEUSDT',
  'WIFUSDT',
  'WLDUSDT',
  'TAOUSDT',
  'SEIUSDT',
  'TIAUSDT',
  'JUPUSDT',
  'PENDLEUSDT',
  'ENAUSDT',
  'BCHUSDT',
  'ETCUSDT',
  'XLMUSDT',
  'HBARUSDT',
  'ALGOUSDT',
  'VETUSDT',
  'SANDUSDT',
  'MANAUSDT',
  'AXSUSDT',
  'GALAUSDT',
  'FTMUSDT',
  'EGLDUSDT',
  'FLOWUSDT',
  'RUNEUSDT',
  'STXUSDT',
  'CFXUSDT',
  'ORDIUSDT',
  'BOMEUSDT',
  'NOTUSDT',
  'ZKUSDT',
  'STRKUSDT',
  'BLURUSDT',
  'DYDXUSDT',
  'GMXUSDT',
  'CRVUSDT',
  'LDOUSDT',
  'MKRUSDT',
  'SNXUSDT',
  'COMPUSDT',
  'GRTUSDT',
  'THETAUSDT',
  'EOSUSDT',
  'XTZUSDT',
  'NEOUSDT',
  'IOTAUSDT',
  'ZILUSDT',
  'ONEUSDT',
  'CHZUSDT',
  'ENJUSDT',
  'BATUSDT',
  'ZRXUSDT',
  '1INCHUSDT',
  'CAKEUSDT',
  'ROSEUSDT',
  'KAVAUSDT',
  'ANKRUSDT',
  'CELRUSDT',
  'HOTUSDT',
  'QTUMUSDT',
  'ICXUSDT',
  'ONTUSDT',
  'ZENUSDT',
  'RVNUSDT',
  'DASHUSDT',
  'ZECUSDT',
  'XMRUSDT',
  'KSMUSDT',
  'WAVESUSDT',
  'CELOUSDT',
  'MINAUSDT',
  'ASTRUSDT',
  'MASKUSDT',
  'LPTUSDT',
  'API3USDT',
  'SSVUSDT',
  'RPLUSDT',
  'JTOUSDT',
  'PYTHUSDT',
  'ONDOUSDT',
  'ETHFIUSDT',
  'EIGENUSDT',
  'MOVEUSDT',
  'VIRTUALUSDT',
  'AI16ZUSDT',
  'PNUTUSDT',
  'ACTUSDT',
  'GOATUSDT',
  'USUALUSDT',
  'PENGUUSDT',
  'TRUMPUSDT',
  'HYPEUSDT',
  'KAITOUSDT',
  'BERAUSDT',
  'IPUSDT',
] as const;

/** Max liquid US / NASDAQ (+ NYSE mega) for scanner */
export const SCANNER_US_SYMBOLS = [
  // Mega-cap tech
  'AAPL',
  'MSFT',
  'NVDA',
  'GOOGL',
  'GOOG',
  'AMZN',
  'META',
  'TSLA',
  'AVGO',
  'ORCL',
  'CRM',
  'ADBE',
  'AMD',
  'INTC',
  'QCOM',
  'TXN',
  'MU',
  'AMAT',
  'LRCX',
  'KLAC',
  'ASML',
  'CSCO',
  'IBM',
  'NOW',
  'INTU',
  'ADI',
  'NXPI',
  'MRVL',
  'SNPS',
  'CDNS',
  'ANET',
  'APH',
  'MCHP',
  'ON',
  'MPWR',
  'ARM',
  'SMCI',
  'DELL',
  'HPQ',
  'HPE',
  // Growth / software / internet
  'NFLX',
  'PLTR',
  'SNOW',
  'CRWD',
  'PANW',
  'NET',
  'DDOG',
  'SHOP',
  'UBER',
  'ABNB',
  'COIN',
  'SQ',
  'PYPL',
  'SPOT',
  'DASH',
  'RBLX',
  'U',
  'TTD',
  'ROKU',
  'SNAP',
  'PINS',
  'ZM',
  'DOCU',
  'OKTA',
  'ZS',
  'FTNT',
  'TEAM',
  'WDAY',
  'VEEV',
  'HUBS',
  'MDB',
  'ESTC',
  'CFLT',
  'PATH',
  'AI',
  'SOFI',
  'HOOD',
  'AFRM',
  'UPST',
  'NU',
  'MELI',
  'SE',
  'CPNG',
  'BABA',
  'JD',
  'PDD',
  'BIDU',
  'NIO',
  'XPEV',
  'LI',
  'RIVN',
  'LCID',
  // Finance / payments / consumer
  'JPM',
  'V',
  'MA',
  'BAC',
  'WFC',
  'GS',
  'MS',
  'C',
  'AXP',
  'BLK',
  'SCHW',
  'BX',
  'KKR',
  'APO',
  'BRK-B',
  'WMT',
  'COST',
  'TGT',
  'HD',
  'LOW',
  'MCD',
  'SBUX',
  'NKE',
  'LULU',
  'TJX',
  'ROST',
  'DIS',
  'CMCSA',
  'CHTR',
  'NFLX',
  'KO',
  'PEP',
  'PM',
  'MO',
  'PG',
  'CL',
  'EL',
  'MDLZ',
  'KHC',
  'GIS',
  // Energy / industrial / materials
  'XOM',
  'CVX',
  'COP',
  'SLB',
  'EOG',
  'OXY',
  'MPC',
  'PSX',
  'VLO',
  'BA',
  'CAT',
  'GE',
  'HON',
  'UNP',
  'UPS',
  'FDX',
  'DE',
  'MMM',
  'RTX',
  'LMT',
  'NOC',
  'GD',
  'ETN',
  'EMR',
  'ITW',
  'PH',
  'ROK',
  'CMI',
  'PCAR',
  'CSX',
  'NSC',
  'DAL',
  'UAL',
  'AAL',
  'LUV',
  // Healthcare / biotech
  'UNH',
  'JNJ',
  'LLY',
  'PFE',
  'MRK',
  'ABBV',
  'TMO',
  'ABT',
  'DHR',
  'BMY',
  'AMGN',
  'GILD',
  'VRTX',
  'REGN',
  'ISRG',
  'SYK',
  'MDT',
  'BSX',
  'EW',
  'ZTS',
  'CI',
  'ELV',
  'CVS',
  'HUM',
  'MRNA',
  'BNTX',
  'DXCM',
  'IDXX',
  'IQV',
  'A',
  // Telecom / utilities / RE
  'T',
  'VZ',
  'TMUS',
  'NEE',
  'DUK',
  'SO',
  'D',
  'AEP',
  'SRE',
  'EXC',
  'AMT',
  'PLD',
  'CCI',
  'EQIX',
  'SPG',
  'O',
  'WELL',
  'DLR',
  // Semicap / other growth
  'TSM',
  'UMC',
  'GFS',
  'SWKS',
  'QRVO',
  'TER',
  'ENTG',
  'MKSI',
  'WOLF',
  'RMBS',
  'FSLR',
  'ENPH',
  'SEDG',
  'RUN',
  'PLUG',
  'BE',
  'TTWO',
  'EA',
  'ATVI',
  'WBD',
  'PARA',
  'FOX',
  'FOXA',
] as const;

export const SCANNER_US_UNIQUE = [
  ...new Set(SCANNER_US_SYMBOLS.map((s) => s.toUpperCase())),
] as string[];

/** Global US ETFs via Yahoo */
export const SCANNER_ETF_SYMBOLS = [
  'VOO',
  'QQQ',
  'SPY',
  'SCHD',
  'ARKK',
  'VTI',
  'IWM',
  'EEM',
  'GLD',
  'QQQM',
  'VIG',
  'JEPI',
  'DIA',
  'IEMG',
  'VXUS',
  'BND',
  'TLT',
  'HYG',
  'XLF',
  'XLK',
  'XLE',
  'XLV',
  'SMH',
  'SOXX',
  'IBIT',
  'ETHA',
] as const;

export const ETF_META: Record<string, { style: string }> = {
  VOO: { style: 'S&P 500 · Geniş ABD' },
  QQQ: { style: 'Nasdaq 100 · Teknoloji' },
  SPY: { style: 'S&P 500 · Likidite' },
  SCHD: { style: 'ABD Temettü Hisse' },
  ARKK: { style: 'İnovasyon / Büyüme' },
  VTI: { style: 'Toplam ABD Piyasası' },
  IWM: { style: 'Russell 2000 · Küçük Şirket' },
  EEM: { style: 'Gelişmekte Olan Ülkeler' },
  GLD: { style: 'Altın' },
  QQQM: { style: 'Nasdaq 100 · Maliyet Etkin' },
  VIG: { style: 'Temettü Büyüme' },
  JEPI: { style: 'Opsiyon Gelir / Temettü' },
  DIA: { style: 'Dow Jones 30' },
  IEMG: { style: 'EM Geniş' },
  VXUS: { style: 'Uluslararası Hisse' },
  BND: { style: 'ABD Tahvil' },
  TLT: { style: 'Uzun Vadeli Hazine' },
  HYG: { style: 'Yüksek Getirili Tahvil' },
  XLF: { style: 'Finans Sektörü' },
  XLK: { style: 'Teknoloji Sektörü' },
  XLE: { style: 'Enerji Sektörü' },
  XLV: { style: 'Sağlık Sektörü' },
  SMH: { style: 'Yarı İletken' },
  SOXX: { style: 'Yarı İletken (iShares)' },
  IBIT: { style: 'Bitcoin Spot ETF' },
  ETHA: { style: 'Ethereum Spot ETF' },
};

/** Curated popular TEFAS YAT funds */
export const SCANNER_TEFAS_FUNDS = [
  {
    code: 'AFT',
    style: 'Yabancı Teknoloji Hisse',
    founder: 'Ak Portföy',
  },
  {
    code: 'YAY',
    style: 'Yabancı Teknoloji Hisse',
    founder: 'Yapı Kredi Portföy',
  },
  {
    code: 'TTE',
    style: 'BIST Teknoloji Hisse Yoğun',
    founder: 'İş Portföy',
  },
  {
    code: 'TI2',
    style: 'Hisse Senedi Yoğun',
    founder: 'İş Portföy',
  },
  {
    code: 'BIO',
    style: 'Sürdürülebilirlik Hisse',
    founder: 'İş Portföy',
  },
  {
    code: 'MAC',
    style: 'Hisse Senedi Yoğun',
    founder: 'Marmara Capital',
  },
  {
    code: 'IIH',
    style: 'Hisse Senedi Yoğun',
    founder: 'İstanbul Portföy',
  },
  {
    code: 'NNF',
    style: 'Hisse Senedi Yoğun',
    founder: 'Hedef Portföy',
  },
  {
    code: 'ST1',
    style: 'Hisse Senedi Yoğun',
    founder: 'Strateji Portföy',
  },
  {
    code: 'CPU',
    style: 'Teknoloji Katılım',
    founder: 'Aktif Portföy',
  },
  {
    code: 'TCD',
    style: 'Değişken',
    founder: 'Tacirler Portföy',
  },
  {
    code: 'IPB',
    style: 'Değişken',
    founder: 'İstanbul Portföy',
  },
  {
    code: 'OJK',
    style: 'Altın',
    founder: 'QNB Portföy',
  },
  {
    code: 'GUM',
    style: 'Gümüş Fon Sepeti',
    founder: 'Ak Portföy',
  },
  {
    code: 'AK2',
    style: 'Borçlanma Araçları',
    founder: 'Ak Portföy',
  },
  {
    code: 'PPN',
    style: 'Para Piyasası',
    founder: 'Nurol Portföy',
  },
] as const;

export const SCANNER_TEFAS_CODES = SCANNER_TEFAS_FUNDS.map((f) => f.code);

/** Deterministic sparkline removed — do not invent price history. */
export function buildSparkline(
  _price: number,
  _changePercent: number,
  _seed: string
): number[] {
  return [];
}

export function formatVolumeDisplay(
  volume: number | undefined,
  currency: 'TRY' | 'USD'
): string {
  if (volume == null || !Number.isFinite(volume) || volume <= 0) return '—';
  const prefix = currency === 'TRY' ? '₺' : '$';
  const abs = Math.abs(volume);
  if (abs >= 1e9) return `${prefix}${(abs / 1e9).toFixed(1)}B`;
  if (abs >= 1e6) return `${prefix}${(abs / 1e6).toFixed(1)}M`;
  if (abs >= 1e3) return `${prefix}${(abs / 1e3).toFixed(1)}K`;
  return `${prefix}${abs.toFixed(0)}`;
}
