export type SearchItemKind = 'nav' | 'bist' | 'crypto' | 'fx' | 'us' | 'fon';

export interface SearchCatalogItem {
  id: string;
  label: string;
  keywords: string;
  kind: SearchItemKind;
  href: string;
}

export const SEARCH_CATALOG: SearchCatalogItem[] = [
  {
    id: 'nav-overview',
    label: 'Piyasa özeti',
    keywords: 'home dashboard overview terminal özet',
    kind: 'nav',
    href: '/terminal',
  },
  {
    id: 'nav-bist',
    label: 'BİST',
    keywords: 'bist istanbul stocks',
    kind: 'nav',
    href: '/bist',
  },
  {
    id: 'nav-us',
    label: 'NASDAQ / ABD',
    keywords: 'nasdaq us abd aapl nvda tsla apple',
    kind: 'nav',
    href: '/us',
  },
  {
    id: 'nav-fon',
    label: "Fonlar & ETF'ler",
    keywords: 'tefas fon etf voo qqq spy schd aft yay yatırım fonu',
    kind: 'nav',
    href: '/fon',
  },
  {
    id: 'nav-heatmap',
    label: 'Isı Haritası',
    keywords: 'heatmap ısı haritası bist30',
    kind: 'nav',
    href: '/bist/heatmap',
  },
  {
    id: 'nav-crypto',
    label: 'Crypto',
    keywords: 'crypto bitcoin ethereum',
    kind: 'nav',
    href: '/crypto',
  },
  {
    id: 'nav-fx',
    label: 'Döviz',
    keywords: 'döviz fx dolar euro',
    kind: 'nav',
    href: '/fx/USD-TRY',
  },
  {
    id: 'nav-academy',
    label: 'Eğitim Hub',
    keywords: 'eğitim academy borsa rehber rsi temettü',
    kind: 'nav',
    href: '/egitim',
  },
  {
    id: 'nav-blog',
    label: 'Blog',
    keywords: 'blog analiz haber finans',
    kind: 'nav',
    href: '/blog',
  },
  {
    id: 'nav-compare',
    label: '1v1 Kıyasla',
    keywords: 'compare kıyasla vs benchmark thyao pegasus',
    kind: 'nav',
    href: '/compare',
  },
  {
    id: 'nav-firsatlar',
    label: 'AI Fırsat Alımları',
    keywords: 'fırsat opportunity ai alım sinyal radar canlı',
    kind: 'nav',
    href: '/firsatlar',
  },
  {
    id: 'nav-signals',
    label: 'AI Sinyalleri',
    keywords: 'signals sinyal rsi alım satım radar',
    kind: 'nav',
    href: '/signals',
  },
  {
    id: 'nav-alerts',
    label: 'Alarmlar',
    keywords: 'alerts alarm bildirim rsi',
    kind: 'nav',
    href: '/alerts',
  },
  {
    id: 'nav-portfolio',
    label: 'Portföyüm',
    keywords: 'portfolio portföy holdings',
    kind: 'nav',
    href: '/portfolio',
  },
  {
    id: 'xu100',
    label: 'XU100 · BİST 100',
    keywords: 'xu100 bist100 index',
    kind: 'bist',
    href: '/bist/XU100',
  },
  {
    id: 'thyao',
    label: 'THYAO · Türk Hava Yolları',
    keywords: 'thyao thy airlines',
    kind: 'bist',
    href: '/bist/THYAO',
  },
  {
    id: 'garan',
    label: 'GARAN · Garanti BBVA',
    keywords: 'garan garanti bank',
    kind: 'bist',
    href: '/bist/GARAN',
  },
  {
    id: 'asels',
    label: 'ASELS · Aselsan',
    keywords: 'asels aselsan',
    kind: 'bist',
    href: '/bist/ASELS',
  },
  {
    id: 'eregl',
    label: 'EREGL · Ereğli Demir Çelik',
    keywords: 'eregl eregli steel',
    kind: 'bist',
    href: '/bist/EREGL',
  },
  {
    id: 'btc',
    label: 'BTC · Bitcoin',
    keywords: 'btc bitcoin crypto',
    kind: 'crypto',
    href: '/crypto/BTCUSDT',
  },
  {
    id: 'eth',
    label: 'ETH · Ethereum',
    keywords: 'eth ethereum crypto',
    kind: 'crypto',
    href: '/crypto/ETHUSDT',
  },
  {
    id: 'bnb',
    label: 'BNB · BNB',
    keywords: 'bnb binance',
    kind: 'crypto',
    href: '/crypto/BNBUSDT',
  },
  {
    id: 'sol',
    label: 'SOL · Solana',
    keywords: 'sol solana',
    kind: 'crypto',
    href: '/crypto/SOLUSDT',
  },
  {
    id: 'us-aapl',
    label: 'AAPL · Apple',
    keywords: 'aapl apple nasdaq',
    kind: 'us',
    href: '/us/AAPL',
  },
  {
    id: 'us-msft',
    label: 'MSFT · Microsoft',
    keywords: 'msft microsoft nasdaq',
    kind: 'us',
    href: '/us/MSFT',
  },
  {
    id: 'us-nvda',
    label: 'NVDA · NVIDIA',
    keywords: 'nvda nvidia nasdaq ai',
    kind: 'us',
    href: '/us/NVDA',
  },
  {
    id: 'us-tsla',
    label: 'TSLA · Tesla',
    keywords: 'tsla tesla nasdaq',
    kind: 'us',
    href: '/us/TSLA',
  },
  {
    id: 'us-amzn',
    label: 'AMZN · Amazon',
    keywords: 'amzn amazon nasdaq',
    kind: 'us',
    href: '/us/AMZN',
  },
  {
    id: 'us-meta',
    label: 'META · Meta',
    keywords: 'meta facebook nasdaq',
    kind: 'us',
    href: '/us/META',
  },
  {
    id: 'us-googl',
    label: 'GOOGL · Alphabet',
    keywords: 'googl google alphabet nasdaq',
    kind: 'us',
    href: '/us/GOOGL',
  },
  {
    id: 'fon-aft',
    label: 'AFT · Ak Portföy Yeni Teknolojiler',
    keywords: 'aft ak portföy teknoloji tefas fon',
    kind: 'fon',
    href: '/fon/AFT',
  },
  {
    id: 'fon-yay',
    label: 'YAY · Yapı Kredi Yabancı Teknoloji',
    keywords: 'yay yapı kredi teknoloji tefas fon',
    kind: 'fon',
    href: '/fon/YAY',
  },
  {
    id: 'fon-tte',
    label: 'TTE · İş Portföy BIST Teknoloji',
    keywords: 'tte iş portföy teknoloji tefas',
    kind: 'fon',
    href: '/fon/TTE',
  },
  {
    id: 'etf-voo',
    label: 'VOO · Vanguard S&P 500 ETF',
    keywords: 'voo vanguard sp500 etf',
    kind: 'fon',
    href: '/fon/VOO',
  },
  {
    id: 'etf-qqq',
    label: 'QQQ · Invesco Nasdaq 100',
    keywords: 'qqq invesco nasdaq etf',
    kind: 'fon',
    href: '/fon/QQQ',
  },
  {
    id: 'etf-schd',
    label: 'SCHD · Schwab US Dividend',
    keywords: 'schd dividend temettü etf',
    kind: 'fon',
    href: '/fon/SCHD',
  },
  {
    id: 'usd',
    label: 'USD/TRY',
    keywords: 'usd dollar döviz fx dolar kaç tl',
    kind: 'fx',
    href: '/fx/USD-TRY',
  },
  {
    id: 'eur',
    label: 'EUR/TRY',
    keywords: 'eur euro döviz fx',
    kind: 'fx',
    href: '/fx/EUR-TRY',
  },
  {
    id: 'gbp',
    label: 'GBP/TRY',
    keywords: 'gbp sterling pound fx',
    kind: 'fx',
    href: '/fx/GBP-TRY',
  },
];
